language: php

dist: precise

sudo: false

php:
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_myapp;'
  - composer run-script post-install-cmd --no-interaction

script:
  - vendor/bin/phpunit
  # removed ./config for now because of missing namespaces in Migrations/seeds.
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c88cdf0f6de78dde746
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
