language: php

sudo: false

php:
  - 7.0

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
    # removed ./config for now because of missing namespaces in Migrations/seeds.
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot"

notifications:
  email: false
