language: php

sudo: false

php:
  - 5.6

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
    # removed ./config for now because of missing namespaces in Migrations/seeds.
  - sh -c "vendor/bin/phpunit"
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c88cdf0f6de78dde746
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
