-- MySQL Workbench Synchronization
-- Generated: 2015-11-18 15:52
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Manuel Tancoigne

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `elabs`.`licenses` 
CHANGE COLUMN `link` `link` VARCHAR(150) NULL DEFAULT NULL COMMENT '' ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
